{
 "title": "Lustre Exporter OSS Detailed",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fs_name",
    "label": "Filesystem",
    "query": {
     "query": "lustre_exports_total{component=\"ost\"}"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(lustre_exports_total{target=~\"$fs_name-OST.*\"}, instance)"
    }
   },
   { "name": "lustre_port", "label": "Lustre-Port", "query": "${VAR_LUSTRE_PORT}" },
   { "name": "node_port", "label": "Node-Port", "query": "${VAR_NODE_PORT}" },
   { "name": "node_job", "label": "Node-Job", "query": "${VAR_NODE_JOB}" },
   { "name": "lustre_job", "label": "Lustre-Job", "query": "${VAR_LUSTRE_JOB}" }
  ]
 },
 "panels": [
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$host:$node_port\",job=~\"$node_job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$host:$node_port\",job=~\"$node_job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$host:$node_port\",job=~\"$node_job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$host:$node_port\",job=~\"$node_job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$host:$node_port\",job=~\"$node_job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$host:$node_port\",job=~\"$node_job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  { "title": "OST Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Read Throughput per OST",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(lustre_read_bytes_total{instance=\"$host:$lustre_port\",job=\"$lustre_job\"}[1m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Write Throughput per OST",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(lustre_write_bytes_total{instance=\"$host:$lustre_port\",job=\"$lustre_job\"}[1m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - ((lustre_available_kilobytes{instance=\"$host:$lustre_port\",job=\"$lustre_job\",component=\"ost\"} / lustre_capacity_kilobytes{instance=\"$host:$lustre_port\",job=\"$lustre_job\",component=\"ost\"}) * 100)",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "I-Node Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - lustre_inodes_free{instance=~\"$host:$lustre_port\",job=\"$lustre_job\", component=\"ost\"} / lustre_inodes_maximum{instance=~\"$host:$lustre_port\",job=\"$lustre_job\", component=\"ost\"} * 100",
       "legendFormat": "{{target}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobstats Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Read Jobs (Throughput > 10MB/s)",
     "type": "graph",
     "description": "Top read jobs aggregated over all OSTs with throughput > 10MB/s",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk(1, sum(irate(lustre_job_read_bytes_total{component=\"ost\",instance=\"$host:$lustre_port\",job=\"$lustre_job\"}[1m])>10000000) by (jobid))",
       "legendFormat": "{{jobid}}"
      }
     ]
    },
    {
     "title": "Top Write Jobs (Throughput > 10MB/s)",
     "type": "graph",
     "description": "Top write jobs aggregated over all OSTs with throughput > 10MB/s",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk(1, sum(irate(lustre_job_write_bytes_total{component=\"ost\",instance=\"$host:$lustre_port\",job=\"$lustre_job\"}[1m])>10000000) by (jobid))",
       "legendFormat": "{{jobid}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Count",
     "type": "graph",
     "description": "Count of processes involved in IO operations on the file server",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "count(irate(lustre_job_read_bytes_total{component=\"ost\",instance=\"$host:$lustre_port\",job=\"$lustre_job\"}[1m]) > 0)",
       "legendFormat": "read"
      },
      {
       "expr": "count(irate(lustre_job_write_bytes_total{component=\"ost\",instance=\"$host:$lustre_port\",job=\"$lustre_job\"}[1m]) > 0)",
       "legendFormat": "write"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "InfiniBand RDMA Bandwith",
     "type": "graph",
     "description": "RDMA InfiniBand Bandwith over all NIC",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_infiniband_port_data_received_bytes_total{instance=~\"$host:$node_port\",job=\"$node_job\"}[1m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(irate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$host:$node_port\",job=\"$node_job\"}[1m]))",
       "legendFormat": "Transmitted"
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Degraded",
     "type": "timeseries",
     "description": "Binary indicator as to whether or not the pool is degraded - 0 for not degraded, 1 for degraded",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "lustre_degraded{instance=\"$host:$lustre_port\", job=\"$lustre_job\"}",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "Healthy",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "lustre_health_check{instance=~\"$host:$lustre_port\",job=\"$lustre_job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "LNET Errors",
     "type": "timeseries",
     "description": "Count of LNET errors",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(lustre_errors_total{instance=\"$host:$lustre_port\", job=\"$lustre_job\"}[1m])",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  }
 ]
}