{
 "title": "Lustre Exporter MDS Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fs_name", "label": "Filesystem", "query": { "query": "lustre_changelog_current_index" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(lustre_changelog_current_index{target=~\"$fs_name-MDT.*\"}, instance)"
    }
   },
   { "name": "lustre_port", "query": "${VAR_LUSTRE_PORT}" },
   { "name": "node_port", "query": "${VAR_NODE_PORT}" },
   { "name": "node_job", "query": "${VAR_NODE_JOB}" },
   { "name": "lustre_job", "query": "${VAR_LUSTRE_JOB}" }
  ]
 },
 "panels": [
  { "title": "CPU Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load Average (1m resolution)",
   "type": "graph",
   "description": "CPU load average 1 minute with resolution for Lustre Hebe Meta Data Server",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$host:$node_port\",job=~\"$node_job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Metadata Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Metadata Operations per MDT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_stats_total{instance=~\"$host:$lustre_port\",job=\"$lustre_job\", component=\"mdt\"}[120s])) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "I-Nodes Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - lustre_inodes_free{instance=~\"$host:$lustre_port\",job=\"$lustre_job\", component=\"mdt\"} / lustre_inodes_maximum{instance=~\"$host:$lustre_port\",job=\"$lustre_job\", component=\"mdt\"} * 100",
       "legendFormat": "{{instance}}-[{{target}}]"
      }
     ]
    },
    {
     "title": "Disk Space Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - lustre_available_kilobytes{instance=~\"$host:$lustre_port\",job=\"$lustre_job\", component=\"mdt\"} / lustre_capacity_kilobytes{instance=~\"$host:$lustre_port\",job=\"$lustre_job\", component=\"mdt\"} * 100",
       "legendFormat": "{{instance}}-[{{target}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received InfiniBand Network Traffic",
     "type": "graph",
     "description": "Received InfiniBand Network Traffic aggregated over all available IB interfaces (e.g. ib0/ib1)",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_infiniband_port_data_received_bytes_total{instance=~\"$host:$node_port\",job=~\"$node_job\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transmitted InfiniBand Network Traffic",
     "type": "graph",
     "description": "Transmitted InfiniBand Network Traffic aggregated over all available IB interfaces (e.g. ib0/ib1)",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$host:$node_port\",job=~\"$node_job\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Healthy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "lustre_health_check{instance=~\"$host:$lustre_port\",job=\"$lustre_job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LNET Errors",
   "type": "timeseries",
   "description": "Count of LNET errors",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(lustre_errors_total{instance=~\"$host:$lustre_port\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}